version: 2

sources:
  - name: refs
    schema: refs
    tables:
      - name: calendar2
      - name: country_codes_alpha
  - name: api_nbrb_by_exrates
    schema: api_nbrb_by_exrates
    tables:
      - name: rates 

  - name: Stage1CUpp
    schema: Stage1CUpp_stage
    tables:
      - name: "С_ЕдиницыИзмерения"
      - name: "РС_ЗначенияСвойствОбъектов"
      - name: "Д_ЗаказПокупателя"
      - name: "С_Номенклатура" 
      - name: "РН_Продажи"
      - name: "РН_ТоварыНаСкладахОстатки"
      - name: "С_ТорговыеОбъекты"
      - name: "Д_РеализацияТоваровУслуг"
      - name: "С_Контрагенты"
      - name: "Д_ВозвратТоваровОтПокупателя"
      - name: "РС_Штрихкоды"
      - name: "Д_РеализацияТоваровУслугТовары"
        description: "Табличная часть с товарами документов \"РеализацияТоваровУслуг\". Наполняет РН_Продажи"
      - name: "РН_ВыпускПродукции"
      - name: "С_НоменклатурныеГруппы"
      - name: "С_Склады"
      - name: "Д_ПланПроизводства"
      - name: "С_СерииНоменклатуры"
      - name: "С_Регионы"
      - name: "Д_ВозврТовОтПокупатТовары"
      - name: "РН_ТоварыВРезНаСкладОстат"
      - name: "Д_ЗаказПокупателяТовары"
      - name: "РН_ЗаказыПокупателей"

models:
  - name: "stg_C_ТорговыеОбъекты"
    description: "Актуальные торговые объекты из 1С"
    columns:
     - name: "СсылкаГуид"
       description: "Гуид объекта"
       data-tests:
        - not_null
        - unique
  - name: "stg_Д_ЗаказПокупателя"
    description: "Актуальные заказы покупателей из 1С"
    columns:
     - name: "СсылкаГуид"
       description: "Гуид объекта"
       data-tests:
        - not_null
        - unique
  - name: "stg_С_СерииНоменклатуры"
    description: "Серии номенклатуры из 1С"
    columns:
     - name: "СсылкаГуид"
       description: "Гуид объекта"
       data-tests:
        - not_null
        - unique
        