version: 2

models:

  - name: "star_exclude_guid"
    description: "Макрос можно использовать вместо оператора \"*\". Исключает поля содержащие \"Гуид\" и вторым аргументом поля из массива \"additinal_excludes\""
